version: '3.8'
services:
  backend:
    build: ./backend
    container_name: payment_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - tor
      - redis

  frontend:
    build: ./frontend
    container_name: payment_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: payment_db
    environment:
      POSTGRES_DB: payment_system
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  tor:
    image: dperson/torproxy
    container_name: payment_tor
    command: "-socksPort 9050 -hiddenServiceDir /var/lib/tor/tor.service/ -hiddenServicePort 80 127.0.0.1:8080"
    ports:
      - "9050:9050"
    volumes:
      - ./tor:/var/lib/systemd/system/tor.service

  redis:
    image: redis:alpine
    container_name: payment_redis
    ports:
      - "6379:6379"
