version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: core_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  btcpay:
    image: btcpayserver/btcpayserver:latest
    environment:
      BTCPAY_API_KEY: ${BTCPAY_API_KEY}
    ports:
      - "23000:23000"

  monero-wallet:
    image: monero-wallet-rpc
    environment:
      MONERO_WALLET_RPC: ${MONERO_WALLET_RPC}
      MONERO_WALLET_USER: ${MONERO_WALLET_USER}
      MONERO_WALLET_PASSWORD: ${MONERO_WALLET_PASSWORD}
    ports:
      - "18082:18082"

  tor:
    image: dperson/torproxy
    environment:
      TOR_SOCKS_PORT: ${TOR_SOCKS_PORT}
      TOR_CONTROL_PORT: ${TOR_CONTROL_PORT}
      TOR_PASSWORD: ${TOR_PASSWORD}
    ports:
      - "${TOR_SOCKS_PORT}:${TOR_SOCKS_PORT}"
      - "${TOR_CONTROL_PORT}:${TOR_CONTROL_PORT}"

volumes:
  postgres_data:
