// /home/inno/elights_jobes-research/backend/domain/src/lib.rs

// Establish connection with Diesel macros if connection logic is here
// #[macro_use]
// extern crate diesel;
// #[macro_use]
// extern crate diesel_migrations;

pub mod models;
pub mod payments;
pub mod crypto;
pub mod security;
pub mod services;
pub mod error;
pub mod utils; // General utilities for domain logic

// Re-export key types and error for easier access from other crates
pub use error::DomainError;
pub use models::*; // Re-export all models

// Optional: Database connection setup if managed within domain
// pub mod db;
// pub use db::establish_connection;

// Include the generated schema (relative to src/lib.rs)
// Assumes schema.rs is generated in the crate root (../schema.rs)
// or copied/symlinked into src/
// pub mod schema;
// TODO: Ensure schema.rs generated by `diesel print-schema` is accessible here.
// If schema.rs is in ../database/, you might need build scripts or manual copying,
// or define the DB interactions in a separate `database` crate.
// For now, assume models define their table links directly.
// pub mod schema {
//     // Placeholder until schema generation location is confirmed
//     // include!("../../database/schema.rs"); // Example if generated one level up
// }